### PR TITLE
Update package-lock to modern npm version

### PR DESCRIPTION
**Pull request by miniBill**
This is just the result of running `npm install`.

Separating it as its own PR to make the followup ones less noisy.

### CODE REVIEW

**Comment by miniBill** [comment]
*poke*

**Comment by miniBill** [comment]
It's mostly because after this I planned to do another PR updating the dependencies that have security vulnerabilities, and wanted to minimize the diff.

If compatibility with npm < 7 is valuable to you I can just close this and use node 15 for the rest of the work

**Comment by rlefevre** [comment]
It's not valuable to me, but some users tend to lag with Node versions.
It could make sense to update it to the oldest supported Node.js version, so v18.
I guess that users that need older compatibility could just use the currently published version of `elm-doc-preview`.

**Comment by rlefevre** [comment]
I will make the update. It looks like Node 20 is actually needed to get secure versions of all packages.

**Comment by rlefevre** [comment]
v6.0.0 has been released:
https://github.com/dmy/elm-doc-preview/releases/tag/v6.0.0

**Pull request closed without merging**
